import { readPageMedia } from './utils/web-page-media';
import { readTedMedia } from './utils/ted-media';
import { placeWebBar, WEB_BAR_STYLE } from './utils/web-bar-placement';
import type { PanelSegment } from './utils/youtube-panel-actions';
import { BAR_STYLE, buildTranscriptBar, type TranscriptBar } from './utils/youtube-transcript-bar';
import { createTranscriptCache } from './utils/youtube-transcript-cache';
import { createBarGeneration } from './utils/bar-generation';
import { generationStrings } from './utils/subtitle-generation-strings';
import { registerWebSource } from './utils/asr-client';
import { webKey } from './utils/podcast-feed';
import { siteOf } from './utils/study-sites';
import { activeWebMedia, currentWebMediaAddress, declaredWebMediaAddress } from './utils/web-media-page';

// Shared transcript bar for supported media detail pages. On X, on the page of a post that holds a video or audio, the transcript bar sits right under the media, in the post's own
// colours and type: in the right column where X shows its own modules (search, what's happening), or under the media when there is no
// right column (a narrow window). It offers to make subtitles for it (the local helper reads the post with yt-dlp), then shows them following
// playback, and opens study mode. Posts without media get nothing, and neither does the timeline.
declare global { interface Window { qiaomuWebLoaded?: boolean } }

try {
	if (!window.qiaomuWebLoaded) {
		window.qiaomuWebLoaded = true;
		type Api = {
			runtime: { sendMessage(message: unknown): Promise<unknown> | undefined; onMessage: { addListener(listener: (message: { action?: string }, sender: unknown, reply: (value: unknown) => void) => void): void } };
			i18n: { getMessage(key: string): string };
			storage: { local?: { get(keys: string | string[]): Promise<Record<string, any>>; set(items: Record<string, unknown>): Promise<void>; remove(keys: string | string[]): Promise<void> }; sync?: { get(key: string): Promise<Record<string, any>> }; onChanged: { addListener(listener: (changes: Record<string, { newValue?: any }>, area: string) => void): void } };
		};
		const api = (typeof browser !== 'undefined' ? browser : chrome) as unknown as Api;
		const zh = /^zh/i.test(navigator.language);
		const text = (key: string, zhText: string, enText: string) => (key && api.i18n.getMessage(key)) || (zh ? zhText : enText);
		const none = text('xBarNone', '这条内容还没有字幕，可以用语音识别生成', 'No subtitles yet — they can be generated by speech recognition');
		const strings = {
			heading: text('', '乔木剪藏', 'Qiaomu Clipper'), subtitles: text('youtubeBarSubtitles', '字幕', 'Subtitles'), copy: text('youtubePanelCopy', '复制', 'Copy'), download: text('youtubePanelDownload', '下载', 'Download'),
			study: text('youtubePanelStudy', '沉浸学习', 'Study'), settings: text('youtubeBarSettings', '设置', 'Settings'), expand: text('youtubeBarExpand', '展开字幕', 'Show transcript'), collapse: text('youtubeBarCollapse', '收起', 'Collapse'),
			copied: text('youtubePanelCopied', '已复制', 'Copied'), empty: none, reload: text('youtubePanelReload', '扩展刚更新过，请刷新此页面后再试', 'The extension was updated — reload this page and try again'),
			loading: text('youtubePanelCardLoading', '正在读取字幕…', 'Reading the transcript…'), ready: text('youtubePanelCardReady', '字幕已就绪，点击时间可跳转', 'Transcript ready — click a time to jump'), none,
			retry: text('youtubeBarRetry', '重试', 'Retry'), more: text('youtubeBarMore', '更多内容请在沉浸学习里查看', 'Open study mode to read the rest'), search: text('youtubeBarSearch', '搜索字幕', 'Search transcript'),
			clear: text('youtubeBarClear', '清除搜索', 'Clear search'), noMatch: text('youtubeBarNoMatch', '无结果', 'No results'), follow: text('youtubeBarFollow', '字幕跟随播放：开（点击关闭）', 'Following playback — click to turn off'),
			followOff: text('youtubeBarFollowOff', '字幕跟随播放：关（点击开启）', 'Not following — click to follow playback'), here: text('youtubeBarHere', '回到当前位置', 'Back to current line'), language: text('subtitleLanguage', '字幕语言', 'Subtitle language'),
		};
		const cache = api.storage.local ? createTranscriptCache(api.storage.local) : undefined;
		let panelOn = false, siteOn = false; // the viewer can switch this off (the bar setting, or the site in "supported sites")
		let lines: PanelSegment[] = [], state: 'loading' | 'ready' | 'none' | 'generating' = 'loading', bar: TranscriptBar | undefined, host: HTMLElement | undefined, postUrl = '', key = '';

		// The post this page is about, and its first video or audio.
		const isX = siteOf(location.href)?.id === 'x';
		const post = () => { const player = media(); return player ? currentWebMediaAddress(document, player, location.href) : declaredWebMediaAddress(document, location.href); };
		const mainTweet = () => isX ? document.querySelector<HTMLElement>('main article[data-testid="tweet"]') ?? document.querySelector<HTMLElement>('article') : document.body;
		const pageMedia = (url: string) => readPageMedia(document, url, media());
		const media = () => isX ? mainTweet()?.querySelector<HTMLMediaElement>('video, audio') ?? undefined : activeWebMedia(document);
		api.runtime.onMessage.addListener((message, _sender, reply) => { if (message.action === 'qiaomuWebMediaSource') reply({ url: post(), info: pageMedia(post() || '') }); });
		const tweetText = () => (mainTweet()?.querySelector('[data-testid="tweetText"]')?.textContent || document.title).replace(/\s+/g, ' ').trim().slice(0, 120);

		// The colours of the page it sits in: X has a light, a dim and a dark theme, and none of them is ours to choose.
		const paint = (element: HTMLElement, where: 'side' | 'media') => {
			const parts = getComputedStyle(document.body).backgroundColor.match(/\d+(\.\d+)?/g)?.map(Number) ?? [255, 255, 255], dark = (parts[0] * 299 + parts[1] * 587 + parts[2] * 114) / 1000 < 140;
			const set = (name: string, value: string) => element.style.setProperty(name, value);
			set('--qm-bg', dark ? '#16181c' : '#fff');
			if (!isX) { set('--qm-card', dark ? '#16181c' : '#fff'); set('--qm-margin', '0'); }
			if (dark) { set('--qm-fg', '#e7e9ea'); set('--qm-fg2', '#71767b'); set('--qm-line', '#2f3336'); set('--qm-hover', 'rgba(231,233,234,.1)'); set('--qm-field', 'rgba(231,233,234,.08)'); }
			// In the right column it is a card like X's own: a tint of its own, no outline. Under the media it keeps the outline.
			if (where === 'side') { const black = parts[0] + parts[1] + parts[2] < 60; set('--qm-card', dark ? (black ? 'rgb(22,24,28)' : 'rgb(30,39,50)') : 'rgb(247,249,249)'); set('--qm-frame', '0 none'); set('--qm-margin', '0 0 16px'); }
		};
		let officialReady = false;
		const updateBar = () => { bar?.setState(state, lines); if (officialReady) bar?.setGeneration(null); else generation.sync(); };
		const generation = createBarGeneration({
			openSettings: () => { try { void api.runtime.sendMessage({ action: 'openSettings', section: 'asr' }); } catch { /* extension reloaded */ } },
			videoKey: () => key || null, bar: () => bar,
			apply: (_key, made, done) => { lines = made; state = done ? 'ready' : 'generating'; updateBar(); },
			revert: () => { lines = []; state = 'none'; updateBar(); },
			save: (k, made) => { void cache?.write(`generated:${k}`, made); },
		});
		const readOfficial = async (language?: string) => {
			if (siteOf(postUrl)?.id !== 'ted') return;
			return readTedMedia(postUrl, async url => { const reply = await api.runtime.sendMessage({ action: 'fetchProxy', url, options: {} }) as { text?: string }; return reply?.text || ''; }, document, language);
		};
		const load = () => {
			officialReady = false; lines = []; state = 'loading'; updateBar(); const mine = key;
			void (async () => {
				const official = await readOfficial(); if (key !== mine) return;
				if (official?.segments.length) { officialReady = true; lines = official.segments; state = 'ready'; bar?.setLanguages(official.languages, official.language); updateBar(); return; }
				const made = await (cache ? cache.read(`generated:${mine}`) : Promise.resolve(undefined));
				if (key !== mine) return;
				if (made?.length) { lines = made; state = 'ready'; generation.markGenerated(mine); } else state = 'none';
				updateBar();
			})();
		};
		const remove = () => { host?.remove(); host = undefined; bar = undefined; generation.reset(); postUrl = ''; key = ''; };
		// Under the media, above the row of reply / repost / like when it can be found, else at the end of the post.
		// Where in the right column it can go: just above X's own modules (related users, what's happening), which are `aside` blocks listed one
		// after another. Not next to the search box: that is fixed to the top of the column and covers whatever is inserted beside it.
		const sideSpot = (): HTMLElement | undefined => {
			if (!isX) return undefined;
			const side = document.querySelector<HTMLElement>('[data-testid="sidebarColumn"]'); if (!side || side.getBoundingClientRect().width < 240) return undefined;
			const module = side.querySelector<HTMLElement>('aside[role="complementary"]')?.parentElement;
			return module?.parentElement && module.parentElement !== side && side.contains(module.parentElement) ? module : undefined;
		};
		const place = (node: HTMLElement, tweet: HTMLElement): 'side' | 'media' => {
			if (!isX) { placeWebBar(node, media(), siteOf(location.href)?.id || ''); return 'media'; }
			const module = sideSpot();
			if (module) { module.parentElement!.insertBefore(node, module); return 'side'; }
			const actions = tweet.querySelector<HTMLElement>('[role="group"]');
			if (actions?.parentElement && tweet.contains(actions.parentElement)) actions.parentElement.insertBefore(node, actions); else tweet.append(node);
			return 'media';
		};
		let where: 'side' | 'media' | undefined;
		let mounting = false;
		const mount = async () => {
			if (!(panelOn && siteOn)) { if (host) remove(); return; }
			const url = post(), tweet = mainTweet();
			if (!url || !tweet) { if (host) remove(); return; }
			// The right column can appear or go away as the window is resized: the bar follows it.
			if (host?.isConnected && postUrl === url && (where === 'side') === Boolean(sideSpot())) { if (!isX) { registerWebSource(key, url, pageMedia(url)?.audioUrl || pageMedia(url)?.mediaUrl || undefined); placeWebBar(host, media(), siteOf(location.href)?.id || ''); } return; }
			if (mounting) return; mounting = true;
			try {
				if (host) remove();
				const nextKey = await webKey(url); if (post() !== url) return;
				postUrl = url; key = nextKey; registerWebSource(key, url, pageMedia(url)?.audioUrl || pageMedia(url)?.mediaUrl || undefined);
				const style = document.createElement('style'); style.textContent = BAR_STYLE + '.qiaomu-x{display:block;width:100%}' + WEB_BAR_STYLE;
				host = document.createElement('div'); host.className = isX ? 'qiaomu-x' : 'qiaomu-web-bar'; host.append(style);
				bar = buildTranscriptBar(document, {
					strings, title: tweetText, openStudy: () => { try { void api.runtime.sendMessage({ action: 'qiaomuTripleKey', command: 'read' }); return true; } catch { return false; } },
					openSettings: () => { try { void api.runtime.sendMessage({ action: 'openSettings', section: 'video' }); } catch { /* extension reloaded */ } },
					onLanguage: language => { const mine = key; void readOfficial(language).then(official => { if (key !== mine || !official?.segments.length) return; officialReady = true; lines = official.segments; bar?.setLanguages(official.languages, official.language); updateBar(); }); },
					retry: load, seek: seconds => { const player = media(); if (player && 'currentTime' in player) { player.currentTime = seconds; void player.play().catch(() => {}); } },
					getTime: () => { const player = media(); return player && 'currentTime' in player ? player.currentTime : undefined; }, initialOpen: false, theme: 'x',
					generation: { strings: generationStrings(text), actions: { ...generation.actions, request: () => { const player = media(); if (siteOf(location.href)?.id === 'douyin' && player && 'currentSrc' in player && player.currentSrc.startsWith('blob:')) { void api.runtime.sendMessage({ action: 'qiaomuTripleKey', command: 'read' }); return; } generation.actions.request(); } } }, getSegments: async () => lines,
				} as Parameters<typeof buildTranscriptBar>[1]);
				host.append(bar.element); where = place(host, tweet); paint(bar.element, where); load();
			} finally { mounting = false; }
		};
		// X is a single-page app: posts change without a page load, and its markup is rebuilt often, so look again now and then.
		window.setInterval(() => { void mount(); }, 1000); void mount();
		let moving = false;
		const reposition = () => { if (moving) return; moving = true; requestAnimationFrame(() => { moving = false; if (host && !isX) placeWebBar(host, media(), siteOf(location.href)?.id || ''); }); };
		window.addEventListener('resize', reposition, { passive: true }); document.addEventListener('scroll', reposition, { passive: true, capture: true });
		for (const type of ['timeupdate', 'seeked', 'playing']) document.addEventListener(type, event => { if (event.target instanceof HTMLMediaElement && bar && event.target === media()) bar.setTime(event.target.currentTime, event.type === 'seeked'); }, true);
		const applySites = (value?: { off?: unknown }) => { siteOn = !(Array.isArray(value?.off) && (value!.off as unknown[]).includes((siteOf(location.href)?.id ?? ''))); void mount(); };
		api.storage.local?.get('qiaomuStudySites').then(data => applySites(data?.qiaomuStudySites)).catch(() => applySites());
		api.storage.onChanged.addListener((changes, area) => { if (area === 'local' && changes.qiaomuStudySites) applySites(changes.qiaomuStudySites.newValue); if (area === 'sync' && changes.general_settings) { panelOn = changes.general_settings.newValue?.youtubePanelActions !== false; void mount(); } });
		api.storage.sync?.get('general_settings').then(data => { panelOn = data?.general_settings?.youtubePanelActions !== false; void mount(); }).catch(() => { panelOn = true; void mount(); });
	}
} catch {
	// The extension may have been updated while this page was open.
}
