import type { PanelSegment } from './utils/youtube-panel-actions';
import { BAR_STYLE, buildTranscriptBar, type TranscriptBar } from './utils/youtube-transcript-bar';
import { createTranscriptCache } from './utils/youtube-transcript-cache';
import { createBarGeneration } from './utils/bar-generation';
import { generationStrings } from './utils/subtitle-generation-strings';
import { audioKey } from './utils/video-source';

// Runs on Xiaoyuzhou (podcast) episode pages. The page has no transcript of its own, so the bar here only offers to make one
// from the episode's audio (the local helper downloads it and recognises it), keeps it for next time, and opens study mode.
// It floats at the bottom right: the site's layout is not ours to rearrange.
declare global { interface Window { qiaomuPodcastLoaded?: boolean } }

try {
	if (!window.qiaomuPodcastLoaded) {
		window.qiaomuPodcastLoaded = true;
		type Api = {
			runtime: { sendMessage(message: unknown): Promise<unknown> | undefined };
			i18n: { getMessage(key: string): string };
			storage: { local?: { get(keys: string | string[]): Promise<Record<string, any>>; set(items: Record<string, unknown>): Promise<void>; remove(keys: string | string[]): Promise<void> }; sync?: { get(key: string): Promise<Record<string, any>> }; onChanged: { addListener(listener: (changes: Record<string, { newValue?: any }>, area: string) => void): void } };
		};
		const api = (typeof browser !== 'undefined' ? browser : chrome) as unknown as Api;
		const zh = /^zh/i.test(navigator.language);
		const text = (key: string, zhText: string, enText: string) => (key && api.i18n.getMessage(key)) || (zh ? zhText : enText);
		const none = text('podcastBarNone', '这集节目还没有字幕，可以用语音识别生成', 'No subtitles yet — they can be generated by speech recognition');
		const strings = {
			heading: text('', '乔木剪藏', 'Qiaomu Clipper'), subtitles: text('youtubeBarSubtitles', '字幕', 'Subtitles'), copy: text('youtubePanelCopy', '复制', 'Copy'), download: text('youtubePanelDownload', '下载', 'Download'),
			study: text('youtubePanelStudy', '沉浸学习', 'Study'), settings: text('youtubeBarSettings', '设置', 'Settings'), expand: text('youtubeBarExpand', '展开字幕', 'Show transcript'), collapse: text('youtubeBarCollapse', '收起', 'Collapse'),
			copied: text('youtubePanelCopied', '已复制', 'Copied'), empty: none, reload: text('youtubePanelReload', '扩展刚更新过，请刷新此页面后再试', 'The extension was updated — reload this page and try again'),
			loading: text('youtubePanelCardLoading', '正在读取字幕…', 'Reading the transcript…'), ready: text('youtubePanelCardReady', '字幕已就绪，点击时间可跳转', 'Transcript ready — click a time to jump'), none,
			retry: text('youtubeBarRetry', '重试', 'Retry'), more: text('youtubeBarMore', '更多内容请在沉浸学习里查看', 'Open study mode to read the rest'), search: text('youtubeBarSearch', '搜索字幕', 'Search transcript'),
			clear: text('youtubeBarClear', '清除搜索', 'Clear search'), noMatch: text('youtubeBarNoMatch', '无结果', 'No results'), follow: text('youtubeBarFollow', '字幕跟随播放：开（点击关闭）', 'Following playback — click to turn off'),
			followOff: text('youtubeBarFollowOff', '字幕跟随播放：关（点击开启）', 'Not following — click to follow playback'), here: text('youtubeBarHere', '回到当前位置', 'Back to current line'), language: text('subtitleLanguage', '字幕语言', 'Subtitle language'),
		};
		const cache = api.storage.local ? createTranscriptCache(api.storage.local) : undefined;
		const audio = () => document.querySelector<HTMLAudioElement>('audio') ?? undefined;
		const episodeKey = () => audioKey(location.href);
		const titleOf = () => (document.querySelector('h1')?.textContent || document.title).trim();
		let lines: PanelSegment[] = [], state: 'loading' | 'ready' | 'none' | 'generating' = 'loading', bar: TranscriptBar | undefined, barKey = '', host: HTMLElement | undefined;

		const updateBar = () => { bar?.setState(state, lines); generation.sync(); };
		const generation = createBarGeneration({
			openSettings: () => { try { void api.runtime.sendMessage({ action: 'openSettings', section: 'video' }); } catch { /* extension reloaded */ } },
			videoKey: episodeKey, bar: () => bar,
			apply: (_key, made, done) => { lines = made; state = done ? 'ready' : 'generating'; updateBar(); },
			revert: () => { lines = []; state = 'none'; updateBar(); },
			save: (key, made) => { void cache?.write(`generated:${key}`, made); },
		});
		const load = (key: string) => {
			lines = []; state = 'loading'; updateBar();
			void (cache ? cache.read(`generated:${key}`) : Promise.resolve(undefined)).then(made => {
				if (episodeKey() !== key) return;
				if (made?.length) { lines = made; state = 'ready'; generation.markGenerated(key); } else state = 'none';
				updateBar();
			});
		};
		let panelOn = true, siteOn = true; // the viewer can switch this site off in the settings
		// Below the episode's title and details, above the show notes: where the eye goes next. If the site's layout changes and that
		// spot is gone, the bar floats at the bottom right instead of disappearing.
		const place = (node: HTMLElement): boolean => {
			const header = document.querySelector('main > header') ?? document.querySelector('main header');
			if (header?.parentElement) { header.after(node); return true; }
			const notes = document.querySelector('section[aria-label*="show notes" i], section[aria-label*="节目"]');
			if (notes?.parentElement) { notes.parentElement.before(node); return true; }
			return false;
		};
		const mount = () => {
			const key = episodeKey();
			if (!(panelOn && siteOn)) return;
			if (!key) { host?.remove(); host = undefined; bar = undefined; barKey = ''; return; }
			if (barKey === key && host?.isConnected) return;
			host?.remove(); generation.reset(); barKey = key;
			const style = document.createElement('style'); style.textContent = BAR_STYLE + '.qiaomu-podcast.is-floating{position:fixed;right:20px;bottom:88px;z-index:2147483000;width:min(380px,calc(100vw - 40px));max-height:70vh;overflow:auto;border-radius:14px;box-shadow:0 8px 32px rgba(0,0,0,.18)}.qiaomu-podcast .qiaomu-yt-bar{margin:16px 0}.qiaomu-podcast.is-floating .qiaomu-yt-bar{margin:0}';
			host = document.createElement('div'); host.className = 'qiaomu-podcast'; host.append(style);
			const study = () => { try { void api.runtime.sendMessage({ action: 'qiaomuTripleKey', command: 'read' }); return true; } catch { return false; } };
			bar = buildTranscriptBar(document, {
				strings, title: titleOf, openStudy: study, openSettings: () => { try { void api.runtime.sendMessage({ action: 'openSettings', section: 'video' }); } catch { /* extension reloaded */ } },
				retry: () => load(key), seek: seconds => { const player = audio(); if (player) { player.currentTime = seconds; void player.play().catch(() => {}); } },
				getTime: () => audio()?.currentTime, initialOpen: false, theme: 'podcast',
				generation: { strings: generationStrings(text), actions: generation.actions },
				getSegments: async () => lines,
			} as Parameters<typeof buildTranscriptBar>[1]);
			host.append(bar.element);
			if (!place(host)) { host.classList.add('is-floating'); document.body.append(host); }
			load(key);
		};
		// The site is a single-page app: the episode can change without a page load.
		window.setInterval(mount, 1000); mount();
		for (const type of ['timeupdate', 'seeked', 'playing']) document.addEventListener(type, event => { if (event.target instanceof HTMLAudioElement && bar) bar.setTime(event.target.currentTime, event.type === 'seeked'); }, true);
		const refresh = () => { if (!(panelOn && siteOn)) { host?.remove(); host = undefined; bar = undefined; barKey = ''; } else mount(); };
		const apply = (settings?: { youtubePanelActions?: boolean }) => { panelOn = settings?.youtubePanelActions !== false; refresh(); };
		const applySites = (value?: { off?: unknown }) => { siteOn = !(Array.isArray(value?.off) && (value!.off as unknown[]).includes('xiaoyuzhou')); refresh(); };
		api.storage.local?.get('qiaomuStudySites').then(data => applySites(data?.qiaomuStudySites)).catch(() => {});
		api.storage.onChanged.addListener((changes, area) => { if (area === 'local' && changes.qiaomuStudySites) applySites(changes.qiaomuStudySites.newValue); });
		api.storage.sync?.get('general_settings').then(data => apply(data?.general_settings)).catch(() => {});
	}
} catch {
	// The extension may have been updated while this page was open.
}
